# Generated by Django 5.0.6 on 2025-05-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='menus',
            new_name='menu',
        ),
    ]
