# Generated by Django 5.0.6 on 2025-03-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_vendor_logo_alter_vendor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='featured_images/'),
        ),
    ]
