# Generated by Django 5.0.6 on 2025-05-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_menuitem_menu_menuitem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ManyToManyField(blank=True, to='restaurants.menu'),
        ),
    ]
