# Generated by Django 5.0.6 on 2025-03-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_menu_image_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='featured_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='featured_images/'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='vendor_logos/'),
        ),
    ]
