# Generated by Django 5.0.6 on 2025-03-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_menu_image_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='featured_image',
        ),
    ]
