# Generated by Django 5.0.6 on 2025-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_menu_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
