# Generated by Django 5.0.6 on 2025-03-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
